/*
CREATE TABLE IF NOT EXISTS banners (
  id SERIAL PRIMARY KEY,
  banner_url TEXT NOT NULL,
  banner_title VARCHAR(255) NOT NULL,
  alt_text VARCHAR(255),
  position VARCHAR(100) NOT NULL,
  action TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
*/