CREATE TABLE IF NOT EXISTS taxonomy (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(100) UNIQUE NOT NULL,  
  title VARCHAR(200) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS terms (
  id SERIAL PRIMARY KEY,
  taxonomy_id INTEGER REFERENCES taxonomy(id) ON DELETE CASCADE,
  slug VARCHAR(100) NOT NULL,
  title VARCHAR(200) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS taxonomy_relationships (
    id SERIAL PRIMARY KEY,
    term_id INT REFERENCES terms(id) ON DELETE CASCADE,
    taxonomy_id INT REFERENCES taxonomy(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL,      
    type_id INT NOT NULL,           
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE terms
ADD COLUMN parent_id INT REFERENCES terms(id) ON DELETE SET NULL;

ALTER TABLE taxonomy ADD COLUMN type TEXT[] DEFAULT '{}';

ALTER TABLE terms ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
